print('Напишите величины сторон a и b')
a=int(input())
b=int(input())
print('Ваша площадь равна ', a*b, ', а периметр равен ', (a+b)*2, '. Для завершения программы нажмите ENTER')
input('press ENTER to exit')
